---
- name: Install HTTP server on ubuntu
  hosts: s1, s2
  become: yes

  tasks:
  - name: Install apache2
    apt:
      name: apache2
      state: present

  - name: Start apache2
    service:
      name: apache2
      state: started   

  - name: Enable apache2
    service:
      name: apache2
      enabled: yes
      
...
