---
- name: Install HTTP server
  hosts: g3
  become: yes

  tasks:
  - name: Install HTTPD
    dnf:
      name: httpd
      state: present
    when: ansible_distribution == "Amazon"  

  - name: Start HTTPD
    service:
      name: httpd
      state: started
    when: ansible_distribution == "Amazon"      

  - name: Enable HTTPD
    service:
      name: httpd
      enabled: yes
    when: ansible_distribution == "Amazon"   

  - name: Install apache2
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"   

  - name: Start apache2
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"     

  - name: Enable apache2
    service:
      name: apache2
      enabled: yes
    when: ansible_distribution == "Ubuntu"


  tasks:
    - name: Check the OS distribution
      debug:
        var: ansible_distribution

    - name: Install Apache HTTP Server on CentOS
      package:
        name: httpd
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Update package lists (Debian)
      command: apt-get update
      when: "'Debian' in ansible_distribution"

    - name: Install Apache HTTP Server on Debian
      yum:
        name: apache2
        state: present
      when: "'Debian' in ansible_distribution"

    - name: Start and enable Apache service
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd  # CentOS
        - apache2  # Debian
      when: "'CentOS' in ansible_distribution or 'Debian' in ansible_distribution"

...  

