---
  - name: Update Static page
    copy:
      src: static.html
      dest: /var/www/html/static.html
      force: yes

  - name: Update Dynamic page
    template:
      src: dynamic.j2
      dest: /var/www/html/dynamic.html
      force: yes
...      